packages:
  - "packages/*"
allowBuilds:
  cypress: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - vitest@4.1.11
  - '@vitest/mocker@4.1.11'
  - js-yaml@3.15.2
overrides:
  js-yaml@>=3.0.0 <3.15.2: ^3.15.2
