packages:
  - "packages/*"
allowBuilds:
  cypress: true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - qs@6.15.4 || 6.16.0
  - fast-uri@3.1.6
overrides:
  fast-uri@>=3.0.0 <3.1.6: ^3.1.6
  fast-uri@>=3.1.2 <3.1.6: ^3.1.6
  fast-uri@>=3.1.3 <3.1.6: ^3.1.6
